#!/bin/bash
# Enable mTLS for PostgreSQL: requires client certificate for all dwitp connections
set -euo pipefail

# Fix TLS key permissions (generated by tls-init as root:root 600)
chmod 600 /etc/dwitp/tls/postgres/postgres.key 2>/dev/null || true
chmod 600 /etc/dwitp/tls/ca/ca.key 2>/dev/null || true
chown postgres:postgres /etc/dwitp/tls/postgres/postgres.key 2>/dev/null || true
chown postgres:postgres /etc/dwitp/tls/ca/ca.key 2>/dev/null || true

PG_HBA="$PGDATA/pg_hba.conf"

if [ -f "$PG_HBA" ]; then
    # Add hostssl entry that requires client cert before the default md5 entry
    sed -i '/^host\s\+all\s\+all\s\+all\s\+md5/i\
# DWITP mTLS: require client certificate for SSL connections\
hostssl dwitp dwitp 172.22.0.0/24 cert clientcert=1\
hostssl dwitp dwitp ::1/128 cert clientcert=1' "$PG_HBA"

    # Reload configuration
    pg_ctl reload -D "$PGDATA" 2>/dev/null || true
fi
